FROM ruby:2.4

WORKDIR /usr/src

COPY ./.git /usr/src/.git
COPY ./jekyll /usr/src

RUN bundle install

CMD ["bundle", "exec", "jekyll", "serve", "--port", "80", "--host", "0.0.0.0", "--future", "true"]

EXPOSE 80
