FROM ruby:2.4 as jekyll

WORKDIR /usr/src

COPY ./Gemfile /usr/src/Gemfile
COPY ./Gemfile.lock /usr/src/Gemfile.lock

RUN bundle install

COPY ./ /usr/src/

RUN bundle exec jekyll build --destination _site

FROM nginx:1.13

COPY --from=jekyll /usr/src/_site /usr/share/nginx/html

EXPOSE 80
