FROM ruby:2.4

WORKDIR /usr/src

COPY ./Gemfile /usr/src/Gemfile
COPY ./Gemfile.lock /usr/src/Gemfile.lock

RUN bundle install

COPY ./ /usr/src/

CMD ["bundle", "exec", "jekyll", "serve", "--port", "80", "--host", "0.0.0.0", "--future", "true"]

EXPOSE 80
